- name: play level varaible
  hosts: local
  connection: local
  vars:                                       # global access varibles
    COURSE: DevOps with AWS 
    DURATION: 10hrs
    TRAINER: NARENDRA_L
  tasks:
  - name: print the Course Info     # local access can override
    vars:
      COURSE: ANSIBLE     # inthis course info is over ride the course the variabale  # like inheritance concept
    ansible.builtin.debug:
    #VARS REFERENCE SHOULD BE SOURROUNDED BY ""
      msg: "hello ::{{ COURSE}} ,Course :: {{ DURATION }} Trainer is:: {{ TRAINER }}"

  
  - name: print the Course Info
    ansible.builtin.debug:                        # but in this "course" variable is will print like "aws with ansible"
    #VARS REFERENCE SHOULD BE SOURROUNDED BY ""
      msg: "hello {{ COURSE}} ,Course {{ DURATION }} Trainer is {{ TRAINER }}"