- name: loops using ansible
  hosts: local
  connection: local
  tasks:
  - name: loop the variables
    ansible.builtin.debug:
      msg: "  {{ item }} "  # reser keyword - item
    loop:
    - Narendra
    - AWS
    - Linux
    - GIT
    - GITHUB
