- name: loops using ansible
  hosts:  local
  become: yes
  connection: local
  tasks:
  - name: install pacakages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - zip
