- name: loops using ansible
  become: yes
  hosts: frontend
  tasks:
  - name: install pacakages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: mysql, state: present }
    - { nmae: nginx, state: absent }
    - { name: zip, state: absent }