# - name: loops using ansible
#   hosts: frontend
#   become: yes
#   tasks: 
#   - name: install_pacakages
#     ansible.builtin.pacakage:
#       name: "{{ item.name }}"
#       state: "{{ item.state }}"
#     loop:
#     - { name: 'mysql', state: 'present' }
#     - { nmae: 'nginx', state: 'present' }
#     - { name: 'zip', state: 'present' }

- name: install packages
  hosts: frontend
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'nginx', state: 'present'}
    - { name: 'mysql', state: 'absent'}
    - { name: 'zip', state: 'absent'}

- name: install package
  hosts: frontend
  become: yes
  tasks:
  - name: install-pacakages
    ansible.builtin.package:
      name: " {{  item.name }} "
      state: " {{  item.state  }} "
    loop:
    - { name: 'nginx', satate: 'absent'  }
    - { name: 'zip', satate: 'absent'  }