- name: loops using ansible
  become: yes
  hosts: local
  connection: local
  tasks:
  - name: install pacakages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'present' }
    - { nmae: 'nginx', state: 'absent' }
    - { name: 'zip', state: 'absent' }